# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  cypress_test:
    name: Run on chrome 83
    runs-on: ubuntu-18.04
    container: cypress/browsers:node12.18.0-chrome83-ff77
    steps:
        -uses: actions/checkout@v2
        
        -name: Install Cypress and verify
          run: |
            npm ci
            $(npm bin)/cypress verify
          
        -name: Run Cypress Tests
          run: npm run test:chrome
          continue-on-error: false
          
        -name: Copy test execution videos and screenshots
          run: |
            mkdir public
            cp -r cypress/videos public/videos
            cp -r cypress/screenshots public/screenshots
            
        -name: Merge Test Reports
          run: npm run combine:report
          
        -name: Generate HTML report
          run: npm run generate:report          
              
        -name: Deploy report page to github page 
         uses: peaceiris/actions-gh-pages@v3
         with: 
            github_token: ${{secrets.GITHUB_TOKEN }}
            publish_dir: .public
